# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4af8d3974f1c2430dc42b880d6e5147"
name = "Dev - Daily Dose HCP"
application_url = "https://rr-dd-poc.colinxr.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers,read_draft_orders,write_draft_orders,read_orders,write_orders,unauthenticated_write_customers,write_app_proxy"

[app_proxy]
url = "https://rr-dd-poc.colinxr.workers.dev/hcp"
prefix = "apps"
subpath = "hcp"

[auth]
redirect_urls = [ "https://rr-dd-poc.colinxr.workers.dev/api/auth" ]
