# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c5b1c7482d9d6c66260198d61698d5d2"
name = "Dose Daily HCP "
application_url = "https://rr-dd-poc.colinxr.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-daily-dose-hcp.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,unauthenticated_write_customers,write_app_proxy,write_customers,write_draft_orders,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://rr-dd-poc.colinxr.workers.dev/api/auth" ]

[app_proxy]
url = "https://rr-dd-poc.colinxr.workers.dev/hcp"
subpath = "hcp"
prefix = "apps"
