name = "rr-dd-poc"
main = "./build/server/index.js"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:worker"

[[d1_databases]]
binding = "DB"
database_name = "rr-dd-poc-db"
database_id = "50a4b203-ffc3-4cc4-9d43-25a992b88bb9"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
